### ISSUE TITLE
Request para retornar os pontos de parada de cada linha

### ISSUE THREAD

**Issue by macecchi** [RioBus/proxy#11]
Criar serviço no rest para retornar apenas os pontos de parada da linha, de maneira similar ao serviço do itinerário da linha.

Exemplo de uso: usuário do app mobile visualiza onde a linha que pesquisou faz paradas.

**Comment by fmsouza** [comment]
Fechado por 6c1e4ab3b97bfe8fcc748bd76b9d4d29c83a21bd
