### ISSUE TITLE
Analisar User-Agent nos analytics de cada request

### ISSUE THREAD

**Issue by macecchi** [RioBus/proxy#12]
Cada cliente incluiria o campo User-Agent nos requests para o servidor REST, por exemplo:
- User-Agent: riobus-web-1.0
- User-Agent: riobus-ios-3.0
- User-Agent: riobus-android-2.0

No node é possível ler esse header usando `req.headers['user-agent']`
Referência: http://stackoverflow.com/questions/3895434/how-to-get-information-about-the-client-in-node-js

**Comment by fmsouza** [comment]
Resolvido pelo commit 2d36c0ba89d08ea93c0a80b80ce7d0a41e6e27b6
