### ISSUE TITLE
Pesquisa por algumas linhas retorna ônibus duplicados

### ISSUE THREAD

**Issue by macecchi** [RioBus/proxy#19]
Ex: http://rest.riob.us/v3/search/551

![screen shot 2015-10-21 at 01 29 35](https://cloud.githubusercontent.com/assets/5282467/10626990/34a2d35e-7793-11e5-9cd4-5ec5b0ca840e.png)

**Comment by fmsouza** [comment]
Como o proxy simplesmente busca, o problema está no data-provider, que pode
estar salvando duplicado.
Em 21/10/2015 01:29, "Mario Cecchi" notifications@github.com escreveu:

**Comment by macecchi** [comment]
Cria um issue lá então :)

**Comment by fmsouza** [comment]
Criada a issue #8 no data-provider: https://github.com/RioBus/data-provider/issues/8
