### ISSUE TITLE
Mostrar pontos de ônibus e quais linhas passam em cada um

### ISSUE THREAD

**Issue by fmsouza** [RioBus/proxy#4]

**Comment by macecchi** [comment]
Desistiu?

**Comment by fmsouza** [comment]
Não, só estou tirando daqui. Ainda ta marcado no Trello. Achei que não cabia estar aqui agora.

—
Frederico Souza
Android Developer
RioBus co-Founder - http://riob.us/ http://riob.us/
Undergraduating in Computer Sciencies in UFRJ
Portfolio - http://fmsouza.github.io/ http://fmsouzagithub.io/
Phone: (+55 21) 97285-8787
Rio de Janeiro, Brazil
