### ISSUE TITLE
Route to /v3/itinerary not working on dev

### ISSUE THREAD

**Issue by macecchi** [RioBus/proxy#42]
http://dev.riob.us:8080/v3/itinerary returns an error. It should return the list of all the available lines such as in http://rest.riob.us/v3/itinerary.

> MongoError: Executor error: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
>    at Object.toError (/app/node_modules/mongodb/lib/mongodb/utils.js:114:11)
>    at /app/node_modules/mongodb/lib/mongodb/cursor.js:689:54
>    at Cursor.close (/app/node_modules/mongodb/lib/mongodb/cursor.js:972:5)
>    at commandHandler (/app/node_modules/mongodb/lib/mongodb/cursor.js:689:21)
>    at /app/node_modules/mongodb/lib/mongodb/db.js:1846:9
>    at Server.Base._callHandler (/app/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
>    at /app/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
>    at MongoReply.parseBody (/app/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
>    at null.<anonymous> (/app/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
>    at emitOne (events.js:90:13)
>    at emit (events.js:182:7)
>    at null.<anonymous> (/app/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
>    at emitTwo (events.js:100:13)
>    at emit (events.js:185:7)
>    at Socket.<anonymous> (/app/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
>    at emitOne (events.js:90:13)

**Comment by fmsouza** [comment]
It also should fulfil the request by returning the following response:

``` typescript
class ItineraryHeader {
   public line: string;
   public description: string;
   public keywords: string;
}

```

**Return:** `ItineraryHeader[]`;

**Comment by fmsouza** [comment]
Actually, as explicated in https://github.com/RioBus/proxy/wiki/REST-API, the correct contract is:

``` typescript
class ItineraryHeader {
   public line: string;
   public description: string;
}

```

**Return:** `ItineraryHeader[]`;
