### ISSUE TITLE
Não mostra erro ao tentar executar com uma porta já usada

### ISSUE THREAD

**Issue by macecchi** [RioBus/proxy#62]
Exemplo: `RIOBUS_SERVER_PORT=27017 npm start` (porta do MongoDB). Ele diz que o server iniciou normalmente, mesmo a porta não estando livre. Obviamente, não funciona. 

Possível que seja bug do próprio express, mas podia testar isso antes de chamar o callback (testar se `server.isListening`?)

**Comment by fmsouza** [comment]
Acho que não tem nada a ver com o express, porque a conexão é criada antes: https://github.com/RioBus/proxy/blob/master/src/app.js#L15

Como o framework de banco que ta sendo usado é o `Robe`, depois vou dar uma olhada pra ver como funciona essa conexão através dele e o que ela retorna (se dá erro quando tem problema).

**Comment by macecchi** [comment]
Mas não tem a ver com o Mongo. Eu só usei a porta dele como exemplo se tentar subir o express numa porta já usada.
